ACS-6304 Try Share with cli scan

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,9 +74,15 @@ jobs:
       - name: Download the Pipeline Scanner
         uses: wei/curl@master
         with:
-          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
+          args: -o pipeline-scan-LATEST.zip https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
       - name: Unzip the Pipeline Scanner
-        run: unzip pipeline-scan-LATEST.zip
+        run: |
+          unzip pipeline-scan-LATEST.zip
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Error: Unzip process failed with exit code $exit_code"
+            exit $exit_code
+          fi
       - name: "Build"
         timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
         run: |
